name: Deploy Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.taskmanager_bot }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@95.164.113.115 << 'EOF'
            cd /home/dave/taskmanager_bot
            git pull origin master
            source venv/bin/activate  
            pip install -r requirements.txt
            sudo systemctl restart taskmanager-bot
          EOF
